# Generated by Django 5.1 on 2024-08-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_librarian_user_alter_reader_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='first_name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reader',
            name='last_name',
            field=models.CharField(default='', max_length=255, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
